=== AlvAnton/curso-Git/cursoGit.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="comandosGit">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comandosConfig">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="comando" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="texto" type="xs:string"/>
                                        <xs:element name="explicacion" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="comandosGenerales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="comando" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="texto" type="xs:string"/>
                                        <xs:element name="explicacion" type="xs:string"/>
                                        <xs:element name="ejemplo" minOccurs="0" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="flujoGit">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="etapas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="etapa" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="explicacion" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comandos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="comando" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="texto" type="xs:string"/>
                                                    <xs:element name="explicacion" type="xs:string"/>
                                                    <xs:element name="ejemplo" minOccurs="0" maxOccurs="unbounded"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="extra">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="objetivo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="paso" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="explicacion" type="xs:string" minOccurs="0"/>
                                                                <xs:element name="ejemplo" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="instruccion" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="fin" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="definicion" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlvAnton/curso-Git/cursoGit.xml
<?xml version="1.0"?>
<comandosGit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="cursoGit.xsd">
    <comandosConfig>
        <comando>
            <texto>git --version</texto>
            <explicacion>
                Nos dice la versión de Git instalada
            </explicacion>
        </comando>

        <comando>
            <texto>git config --global user.name "Alvaro Anton"</texto>
            <explicacion>
                Para poner a Alvaro Anton como usuario global, no de un proyecto en concreto.
            </explicacion>
        </comando>

        <comando>
            <texto>git config --global user.email alvaro.anton.navarrete@gmail.com</texto>
            <explicacion>
                Para poner a alvaro.anton.navarrete@gmail.com como email del usuario global, no de un proyecto en concreto.
            </explicacion>
        </comando>

        <comando>
            <texto>git config --global core.editor "code --wait"</texto>
            <explicacion>
                Para establecer el visual studio code como editor de texto por defecto. --wait indica a la terminal que se quede quieta hasta que
                cerremos el editor de texto.
            </explicacion>
        </comando>

        <comando>
            <texto>git config --global -e</texto>
            <explicacion>
                Para abrir el archivo de configuración global, que en este caso se abrirá en visual studio code porque lo hemos establecido como
                editor de texto por defecto.
            </explicacion>
        </comando>

        <comando>
            <texto>git config --global core.autocrlf true</texto>
            <explicacion>
                Para configurar Git de manera que trate los saltos de línea como se hace en Windows. Si fuera Mac o Linux se escribiría "input" en lugar de "true".
            </explicacion>
        </comando>

        <comando>
            <texto>git config -h</texto>
            <explicacion>
                Da un resumen de lo que se puede añadir a la congifuración de Git.
            </explicacion>
        </comando>
    </comandosConfig>
    
    <comandosGenerales>
        <comando>
            <texto>ls</texto>
            <explicacion>
                Permite listar todos los archivos y carpetas que estén en un determinado directorio, salvo los archivos ocultos. En este caso el comando se refiere al
                directorio en el que estamos en este momento.
            </explicacion>
        </comando>

        <comando>
            <texto>ls -a</texto>
            <explicacion>
                Muestra los archivos ocultos que no salían con el comando "ls" normal.
            </explicacion>
        </comando>

        <comando>
            <texto>pwd</texto>
            <explicacion>
                Nos dice la carpeta (si es Windows) o directorio (si es Mac o Linux) en el que estamos actualmente. Significa "print working directory".
            </explicacion>
        </comando>

        <comando>
            <texto>cd</texto>
            <explicacion>
                Permite cambiar de carpeta/directorio. Después de "cd" se escribe el nombre de la carpeta a la que se quiere cambiar, si se escribe ".." es que se quiere
                volver al directorio padre en la jerarquía.
            </explicacion>
            <ejemplo>cd workspace</ejemplo>
            <ejemplo>cd ..</ejemplo>
            <ejemplo>cd .git</ejemplo>
        </comando>

        <comando>
            <texto>mkdir</texto>
            <explicacion>
                Crea un nuevo directorio. Después del comando se pone el nombre que se le quiere dar al nuevo directorio.
            </explicacion>
        </comando>

        <comando>
            <texto>git init</texto>
            <explicacion>
                Para inicializar un proyecto gestionado con Git. Se ejecuta en el directorio en el que estamos actualmente. Se crea un directorio ".git", ese "."
                significa que es un archivo oculto y no va a aparecer al ejecutar el comando "ls", para que aparezca se necesita "la -a". Al ejecutarse "ls -a" sobre
                nuestro directorio ".git" se muestran todos los archivos que se utiliza en Git para gestionar nuestros proyectos. Todos los commit y todo se almacenará
                aquí, en el ".git". Esto es un detalle de "implementación". 

                La carpeta ".git" generalmente se va a ignorar a la hora de crear repositorios y en una empresa no se va a enviar un servidor central.
            </explicacion>
        </comando>
    </comandosGenerales>

    <flujoGit definicion="El flujo de trabajo que hay que seguir cuando trabajemos con Git">
        <etapas>
            <etapa>
                <nombre>Computador</nombre>
                <explicacion>
                    Cuando trabajemos en el ordenador podremos agregar y modificar todos los archivos que queramos, pero no implica por si solo que estos archivos se
                    vayan a agregar a un repositorio. Para agregar a un repositorio hace falta el comando "git add". Lo que hace ese comando es seleccionar los archivos
                    que queremos agregar a la etapa siguiente, que se llama "stage".

                    IMPORTANTE: si nosotros eliminamos un archivo en el ordenador, también tenemos que ejecutar el comando "git add" y seguir el flujo de trabajo de Git
                    porque es un cambio que tenemos que comprometer para que se vea reflejado en el repositorio. Es decir, si eliminamos el archivo archivo2.txt con el
                    comando "rm archivo2.txt", y ese archivo estaba en la fase "Stage", debemos ejecutar una vez más el comando "git add archivo2.txt" para que el borrado
                    se vea reflejado en el repositorio. Después se hará el commit con el comando "git commit -m "Eliminando el archivo 2"".
                </explicacion>        
            </etapa>

            <etapa>
                <nombre>Stage</nombre>
                <explicacion>
                    Es una etapa intermedia donde se hacen los cambios que queremos que se vean reflejados eventualmente en el repositorio. No todos los cambios van a
                    verse reflejados en el repositorio, solo los que nosotros seleccionemos. Los que no queremos que acaben en el repositorio los podremos sacar, pero
                    cuando tengamos claro con cuáles nos quedamos, podemos pasar a la siguiente etapa ejecutando el comando "git commit".

                    Hay que tener en cuenta una cosa: supongamos que tenemos dos archivos: archivo1.txt con el texto "Chanchito feliz" y archivo2.txt con el texto
                    "Chanchito triste". Supongamos que ejecutamos el comando "git add archivo1.txt archivo2.txt". Esto hará que ambos pasen a la fase "Stage", pero
                    si más tarde hacemos cambios al archivo2.txt, por ejemplo cambiándolo a "Chanchito feliz", al ejecutar "git status" veremos que en los archivos
                    de la fase "Stage", saldrán archivo1.txt y archivo2.txt, y también saldrá archivo2.txt entre los archivos que no pasaron a la fase "Stage". Lo que
                    está ocurriendo es que en la fase "Stage" está la versión de archivo2.txt que subimos a esa fase, pero no la posterior, porque no llegamos a
                    ejecutar el comando "git add archivo2.txt" después de modificar ese archivo. En resumen, en verde saldrá la versión del archivo2.txt que contenga
                    el texto "Chanchito triste", mientras que en rojo saldrá la versión de ese archivo que contenga el texto "Chanchito feliz". Esto sirve para ilustrar
                    cómo Git trabaja con las versiones distintas de los archivos, y de cómo se preparan las distinas versiones para hacer un "commit". Para cambiar esta
                    situación habría que volver a ejecutar un "git add archivo2.txt", en cuyo caso se actualizaría la versión de ese archivo en la fase "Stage" y la
                    versión anterior desaparecería. Esto indica cómo lo que se agrega a la fase "Stage" son cambios.
                </explicacion>
            </etapa>

            <etapa>
                <nombre>Commit</nombre>
                <explicacion>
                    Aquí están los cambios que hemos comprometido. Una vez aquí podemos subirlos a la nube/servidor, que probablemente va a ser gitHub. El comando para
                    subirlos al servidor es "git push".
                </explicacion>
            </etapa>

            <etapa>
                <nombre>Server</nombre>
                <explicacion>
                    Es el servidor en el que se guardan los archivos, generalmente suele ser gitHub.
                </explicacion>
            </etapa>
        </etapas>

        <comandos>
            <comando>
                <texto>code .</texto>
                <explicacion>
                    Hace que visual studio code abra la carpeta en la que estamos actualmente, que se simboliza con el ".". Al hacerlo, podremos ver que visual studio
                    code abre la carpeta, que en este caso sería "miWeb".

                    Una vez en visual studio code, agregamos un nuevo archivo, la extensión no importa porque Git lo puede manejar todo. En este caso creamos el archivo
                    "archivo1.txt" como ejemplo, y escribimos "chanchito feliz".
                </explicacion>
            </comando>

            <comando>
                <texto>git status</texto>
                <explicacion>
                    Nos da un resumen del estado de los archivos del proyecto. Nos dice si ha habido commits, y los archivos a los que no se ha aplicado el comando
                    "git add", y por lo tanto no han pasado a la fase "stage", los llama "untracked files". Los archivos a los que se les ha aplicado el comando
                    "git add" salen en verde bajo el apartado "changes to be committed".
                </explicacion>
